# Generated by Django 3.0.5 on 2020-04-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
